// GENERATED by scripts/fetch-collectables.mjs - do not edit by hand.
import type { MapPin } from "../types";
import pictos from "./pictosPins.json";
import lumina from "./luminaPins.json";
import chroma from "./chromaPins.json";
import chromaCatalysts from "./chroma-catalystsPins.json";
import recoat from "./recoatPins.json";
import weapons from "./weaponsPins.json";
import outfits from "./outfitsPins.json";
import hairstyles from "./hairstylesPins.json";
import tints from "./tintsPins.json";
import journalEntries from "./journal-entriesPins.json";
import musicRecords from "./music-recordsPins.json";
import questItems from "./quest-itemsPins.json";
import paintCages from "./paint-cagesPins.json";
import underwaterTreasure from "./underwater-treasurePins.json";
import lostGestrals from "./lost-gestralsPins.json";

/**
 * Layer pins for the atlas: overworld entries at their projected position,
 * entries inside an area drawn near that area's location pin with `approx`,
 * so the map can show every entry the Library lists.
 */
export const LAYER_PINS: Record<string, MapPin[]> = {
  "pictos": pictos as MapPin[],
  "lumina": lumina as MapPin[],
  "chroma": chroma as MapPin[],
  "chroma-catalysts": chromaCatalysts as MapPin[],
  "recoat": recoat as MapPin[],
  "weapons": weapons as MapPin[],
  "outfits": outfits as MapPin[],
  "hairstyles": hairstyles as MapPin[],
  "tints": tints as MapPin[],
  "journal-entries": journalEntries as MapPin[],
  "music-records": musicRecords as MapPin[],
  "quest-items": questItems as MapPin[],
  "paint-cages": paintCages as MapPin[],
  "underwater-treasure": underwaterTreasure as MapPin[],
  "lost-gestrals": lostGestrals as MapPin[],
};
