// GENERATED by scripts/fetch-collectables.mjs - do not edit by hand.
import type { CollectionEntry } from "../types";
import lumina from "./lumina.json";
import chroma from "./chroma.json";
import chromaCatalysts from "./chroma-catalysts.json";
import recoat from "./recoat.json";
import weapons from "./weapons.json";
import outfits from "./outfits.json";
import hairstyles from "./hairstyles.json";
import tints from "./tints.json";
import journalEntries from "./journal-entries.json";
import musicRecords from "./music-records.json";
import questItems from "./quest-items.json";
import paintCages from "./paint-cages.json";
import underwaterTreasure from "./underwater-treasure.json";
import lostGestrals from "./lost-gestrals.json";

/** Entries per Library layer id, for the layers the reference map sources. */
export const LAYER_ENTRIES: Record<string, CollectionEntry[]> = {
  "lumina": lumina as CollectionEntry[],
  "chroma": chroma as CollectionEntry[],
  "chroma-catalysts": chromaCatalysts as CollectionEntry[],
  "recoat": recoat as CollectionEntry[],
  "weapons": weapons as CollectionEntry[],
  "outfits": outfits as CollectionEntry[],
  "hairstyles": hairstyles as CollectionEntry[],
  "tints": tints as CollectionEntry[],
  "journal-entries": journalEntries as CollectionEntry[],
  "music-records": musicRecords as CollectionEntry[],
  "quest-items": questItems as CollectionEntry[],
  "paint-cages": paintCages as CollectionEntry[],
  "underwater-treasure": underwaterTreasure as CollectionEntry[],
  "lost-gestrals": lostGestrals as CollectionEntry[],
};
